### ISSUE TITLE
Missing module src.loss

### ISSUE THREAD

**Issue by fogonthedowns** [xulisky/dark2keras#1]
```
>>> import dark2keras
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Volumes/data/hack/python/dark2keras/dark2keras.py", line 13, in <module>
    from src.loss.region_loss import region_loss
ModuleNotFoundError: No module named 'src.loss'
```

**Comment by amichayfeldman** [comment]
there is no src\loss folder.
